export interface VocabularyItem {
	word: string;
	translation: string;
	mean: string;
	pronunciation: string;
	example: string;
}

export interface CollectionItemData {
	collectionID: string;
	name: string;
	desc: string;
	value: number;
	date: string;
	vocabulary: VocabularyItem[];
}

export const dummyData: CollectionItemData[] = [
	{
		collectionID: "1",
		name: "Vocabulary of TOEIC Listening",
		desc: "This is a collection of vocabulary of TOEIC Listening",
		value: 7,
		date: "02/2023",
		vocabulary: [
			{
				word: "Home",
				translation: "Nhà ở",
				mean: "The place where you live",
				pronunciation: "ˈhəʊm",
				example: "I live in a home",
			},
			{
				word: "Office",
				translation: "Văn phòng",
				mean: "A place where people work",
				pronunciation: "ˈɒfɪs",
				example: "She works in an office",
			},
			{
				word: "Car",
				translation: "Xe hơi",
				mean: "A vehicle with four wheels",
				pronunciation: "kɑː(r)",
				example: "He drives a car to work",
			},
			{
				word: "Family",
				translation: "Gia đình",
				mean: "A group of people related by blood or marriage",
				pronunciation: "ˈfæm.ɪ.li",
				example: "She spends time with her family on weekends",
			},
			{
				word: "School",
				translation: "Trường học",
				mean: "An institution for educating children",
				pronunciation: "skuːl",
				example: "He goes to school every weekday",
			},
			{
				word: "Book",
				translation: "Sách",
				mean: "A written or printed work consisting of pages",
				pronunciation: "bʊk",
				example: "She reads a book every night before bed",
			},
			{
				word: "Friend",
				translation: "Bạn bè",
				mean: "A person with whom one has a bond of mutual affection",
				pronunciation: "frend",
				example: "She spends time with her friends on weekends",
			},
			{
				word: "Presentation",
				translation: "Bài thuyết trình",
				mean: "A formal talk to a group of people",
				pronunciation: "ˌprɛz.ənˈteɪ.ʃən",
				example: "He gave a presentation at the conference",
			},
			{
				word: "Discussion",
				translation: "Thảo luận",
				mean: "A conversation about a particular topic",
				pronunciation: "dɪˈskʌʃ.ən",
				example: "They had a discussion about the project",
			},
			{
				word: "Question",
				translation: "Câu hỏi",
				mean: "A sentence worded or expressed so as to elicit information",
				pronunciation: "ˈkwes.tʃən",
				example: "She asked a question about the assignment",
			},
			{
				word: "Answer",
				translation: "Trả lời",
				mean: "A reply to a question",
				pronunciation: "ˈɑːn.sər",
				example: "He gave a correct answer to the quiz",
			},
			{
				word: "Interview",
				translation: "Phỏng vấn",
				mean: "A formal meeting in which one or more persons question",
				pronunciation: "ˈɪn.tə.vjuː",
				example: "She had an interview for the job",
			},
			{
				word: "Opinion",
				translation: "Ý kiến",
				mean: "A belief or judgment that rests on grounds insufficient to produce complete certainty",
				pronunciation: "əˈpɪn.jən",
				example: "What is your opinion about the proposal?",
			},
			{
				word: "Topic",
				translation: "Chủ đề",
				mean: "A matter dealt with in a text",
				pronunciation: "ˈtɒp.ɪk",
				example: "They discussed various topics in the meeting",
			},
		],
	},
	{
		collectionID: "2",
		name: "Vocabulary of TOEIC Speaking",
		desc: "This is a collection of vocabulary of TOEIC Speaking",
		value: 7,
		date: "07/2022",
		vocabulary: [
			{
				word: "Presentation",
				translation: "Bài thuyết trình",
				mean: "A formal talk to a group of people",
				pronunciation: "ˌprɛz.ənˈteɪ.ʃən",
				example: "He gave a presentation at the conference",
			},
			{
				word: "Discussion",
				translation: "Thảo luận",
				mean: "A conversation about a particular topic",
				pronunciation: "dɪˈskʌʃ.ən",
				example: "They had a discussion about the project",
			},
			{
				word: "Question",
				translation: "Câu hỏi",
				mean: "A sentence worded or expressed so as to elicit information",
				pronunciation: "ˈkwes.tʃən",
				example: "She asked a question about the assignment",
			},
			{
				word: "Answer",
				translation: "Trả lời",
				mean: "A reply to a question",
				pronunciation: "ˈɑːn.sər",
				example: "He gave a correct answer to the quiz",
			},
			{
				word: "Interview",
				translation: "Phỏng vấn",
				mean: "A formal meeting in which one or more persons question",
				pronunciation: "ˈɪn.tə.vjuː",
				example: "She had an interview for the job",
			},
			{
				word: "Opinion",
				translation: "Ý kiến",
				mean: "A belief or judgment that rests on grounds insufficient to produce complete certainty",
				pronunciation: "əˈpɪn.jən",
				example: "What is your opinion about the proposal?",
			},
			{
				word: "Topic",
				translation: "Chủ đề",
				mean: "A matter dealt with in a text",
				pronunciation: "ˈtɒp.ɪk",
				example: "They discussed various topics in the meeting",
			},
		],
	},
	{
		collectionID: "3",
		name: "Vocabulary of TOEIC Reading",
		desc: "This is a collection of vocabulary of TOEIC Reading",
		value: 7,
		date: "09/2022",
		vocabulary: [
			{
				word: "Article",
				translation: "Bài báo",
				mean: "A piece of writing",
				pronunciation: "ˈɑː.tɪ.kəl",
				example: "He read an interesting article in the newspaper",
			},
			{
				word: "Passage",
				translation: "Đoạn văn",
				mean: "A section of text",
				pronunciation: "ˈpæs.ɪdʒ",
				example: "She read a difficult passage in the book",
			},
			{
				word: "Comprehension",
				translation: "Hiểu biết",
				mean: "The ability to understand",
				pronunciation: "ˌkɒm.prɪˈhen.ʃən",
				example: "He has good comprehension skills",
			},
			{
				word: "Paragraph",
				translation: "Đoạn văn",
				mean: "A distinct section of a piece of writing",
				pronunciation: "ˈpær.ə.ɡrɑːf",
				example: "She wrote a new paragraph in her essay",
			},
			{
				word: "Questionnaire",
				translation: "Bảng câu hỏi",
				mean: "A set of questions",
				pronunciation: "ˌkwes.tʃəˈneər",
				example: "He filled out a questionnaire about his experience",
			},
			{
				word: "Diagram",
				translation: "Sơ đồ",
				mean: "A drawing intended to explain how something works",
				pronunciation: "ˈdaɪ.ə.ɡræm",
				example: "She studied the diagram to understand the process",
			},
			{
				word: "Vocabulary",
				translation: "Từ vựng",
				mean: "A list of words",
				pronunciation: "vəˈkæb.jə.lər.i",
				example: "He expanded his vocabulary by learning new words",
			},
		],
	},
	{
		collectionID: "4",
		name: "Vocabulary of TOEIC Writing",
		desc: "This is a collection of vocabulary of TOEIC Writing",
		value: 7,
		date: "11/2022",
		vocabulary: [
			{
				word: "Essay",
				translation: "Bài luận",
				mean: "A short piece of writing",
				pronunciation: "ˈɛ.seɪ",
				example: "He wrote an essay about his favorite book",
			},
			{
				word: "Introduction",
				translation: "Phần giới thiệu",
				mean: "The opening section of a piece of writing",
				pronunciation: "ˌɪn.trəˈdʌk.ʃən",
				example: "She wrote a clear introduction to her essay",
			},
			{
				word: "Conclusion",
				translation: "Phần kết luận",
				mean: "The final part of something",
				pronunciation: "kənˈkluː.ʒən",
				example: "He summarized his main points in the conclusion",
			},
			{
				word: "Paragraph",
				translation: "Đoạn văn",
				mean: "A distinct section of a piece of writing",
				pronunciation: "ˈpær.ə.ɡrɑːf",
				example: "She wrote a new paragraph in her essay",
			},
			{
				word: "Thesis",
				translation: "Luận văn",
				mean: "A statement or theory that is put forward as a premise",
				pronunciation: "ˈθiː.sɪs",
				example: "She developed a strong thesis for her research paper",
			},
			{
				word: "Argument",
				translation: "Luận điểm",
				mean: "A reason or set of reasons given in support of an idea",
				pronunciation: "ˈɑːɡ.jə.mənt",
				example: "She presented a compelling argument in her essay",
			},
			{
				word: "Revision",
				translation: "Sửa đổi",
				mean: "The action of revising",
				pronunciation: "rɪˈvɪʒ.ən",
				example: "He made several revisions to his essay before submitting it",
			},
		],
	},
	{
		collectionID: "5",
		name: "Vocabulary of IELTS Speaking",
		desc: "This is a collection of vocabulary of IELTS Speaking",
		value: 7,
		date: "04/2023",
		vocabulary: [
			{
				word: "Presentation",
				translation: "Bài thuyết trình",
				mean: "A formal talk to a group of people",
				pronunciation: "ˌprɛz.ənˈteɪ.ʃən",
				example: "She gave a presentation at the conference",
			},
			{
				word: "Discussion",
				translation: "Thảo luận",
				mean: "A conversation about a particular topic",
				pronunciation: "dɪˈskʌʃ.ən",
				example: "They had a discussion about the project",
			},
			{
				word: "Question",
				translation: "Câu hỏi",
				mean: "A sentence worded or expressed so as to elicit information",
				pronunciation: "ˈkwes.tʃən",
				example: "She asked a question about the assignment",
			},
			{
				word: "Answer",
				translation: "Trả lời",
				mean: "A reply to a question",
				pronunciation: "ˈɑːn.sər",
				example: "He gave a correct answer to the quiz",
			},
			{
				word: "Interview",
				translation: "Phỏng vấn",
				mean: "A formal meeting in which one or more persons question",
				pronunciation: "ˈɪn.tə.vjuː",
				example: "She had an interview for the job",
			},
			{
				word: "Opinion",
				translation: "Ý kiến",
				mean: "A belief or judgment that rests on grounds insufficient to produce complete certainty",
				pronunciation: "əˈpɪn.jən",
				example: "What is your opinion about the proposal?",
			},
			{
				word: "Topic",
				translation: "Chủ đề",
				mean: "A matter dealt with in a text",
				pronunciation: "ˈtɒp.ɪk",
				example: "They discussed various topics in the meeting",
			},
		],
	},
	{
		collectionID: "6",
		name: "Vocabulary of TOEFL Listening",
		desc: "This is a collection of vocabulary of TOEFL Listening",
		value: 7,
		date: "03/2023",
		vocabulary: [
			{
				word: "Presentation",
				translation: "Bài thuyết trình",
				mean: "A formal talk to a group of people",
				pronunciation: "ˌprɛz.ənˈteɪ.ʃən",
				example: "She gave a presentation at the conference",
			},
			{
				word: "Accommodate",
				translation: "Đáp ứng",
				mean: "To provide with a place to live or stay",
				pronunciation: "əˈkɒm.ə.deɪt",
				example: "The hotel can accommodate up to 200 guests",
			},
			{
				word: "Advocate",
				translation: "Ủng hộ",
				mean: "To support or recommend publicly",
				pronunciation: "ˈæd.və.keɪt",
				example: "The organization advocates for children's rights",
			},
			{
				word: "Commence",
				translation: "Bắt đầu",
				mean: "To begin or start",
				pronunciation: "kəˈmɛns",
				example: "The ceremony will commence at 9 a.m.",
			},
			{
				word: "Comply",
				translation: "Tuân thủ",
				mean: "To act in accordance with a rule or instruction",
				pronunciation: "kəmˈplaɪ",
				example: "All employees must comply with the safety regulations",
			},
			{
				word: "Constitute",
				translation: "Cấu thành",
				mean: "To be the components or elements of something",
				pronunciation: "ˈkɒn.stɪ.tʃuːt",
				example: "Water and minerals constitute the majority of the human body",
			},
			{
				word: "Contradict",
				translation: "Mâu thuẫn",
				mean: "To be in opposition to or deny the truth of",
				pronunciation: "ˌkɒn.trəˈdɪkt",
				example: "The witness's statement contradicted the evidence",
			},
		],
	},
	{
		collectionID: "7",
		name: "Vocabulary of TOEFL Speaking",
		desc: "This is a collection of vocabulary of TOEFL Speaking",
		value: 7,
		date: "04/2023",
		vocabulary: [
			{
				word: "Presentation",
				translation: "Bài thuyết trình",
				mean: "A formal talk to a group of people",
				pronunciation: "ˌprɛz.ənˈteɪ.ʃən",
				example: "She gave a presentation at the conference",
			},
			{
				word: "Discussion",
				translation: "Thảo luận",
				mean: "A conversation about a particular topic",
				pronunciation: "dɪˈskʌʃ.ən",
				example: "They had a discussion about the project",
			},
			{
				word: "Question",
				translation: "Câu hỏi",
				mean: "A sentence worded or expressed so as to elicit information",
				pronunciation: "ˈkwes.tʃən",
				example: "She asked a question about the assignment",
			},
			{
				word: "Answer",
				translation: "Trả lời",
				mean: "A reply to a question",
				pronunciation: "ˈɑːn.sər",
				example: "He gave a correct answer to the quiz",
			},
			{
				word: "Interview",
				translation: "Phỏng vấn",
				mean: "A formal meeting in which one or more persons question",
				pronunciation: "ˈɪn.tə.vjuː",
				example: "She had an interview for the job",
			},
			{
				word: "Opinion",
				translation: "Ý kiến",
				mean: "A belief or judgment that rests on grounds insufficient to produce complete certainty",
				pronunciation: "əˈpɪn.jən",
				example: "What is your opinion about the proposal?",
			},
			{
				word: "Topic",
				translation: "Chủ đề",
				mean: "A matter dealt with in a text",
				pronunciation: "ˈtɒp.ɪk",
				example: "They discussed various topics in the meeting",
			},
		],
	},
	{
		collectionID: "8",
		name: "Vocabulary of IELTS Writing",
		desc: "This is a collection of vocabulary of IELTS Writing",
		value: 7,
		date: "06/2023",
		vocabulary: [
			{
				word: "Essay",
				translation: "Bài luận",
				mean: "A short piece of writing",
				pronunciation: "ˈɛ.seɪ",
				example: "He wrote an essay about his favorite book",
			},
			{
				word: "Introduction",
				translation: "Phần giới thiệu",
				mean: "The opening section of a piece of writing",
				pronunciation: "ˌɪn.trəˈdʌk.ʃən",
				example: "She wrote a clear introduction to her essay",
			},
			{
				word: "Conclusion",
				translation: "Phần kết luận",
				mean: "The final part of something",
				pronunciation: "kənˈkluː.ʒən",
				example: "He summarized his main points in the conclusion",
			},
			{
				word: "Paragraph",
				translation: "Đoạn văn",
				mean: "A distinct section of a piece of writing",
				pronunciation: "ˈpær.ə.ɡrɑːf",
				example: "She wrote a new paragraph in her essay",
			},
			{
				word: "Thesis",
				translation: "Luận văn",
				mean: "A statement or theory that is put forward as a premise",
				pronunciation: "ˈθiː.sɪs",
				example: "She developed a strong thesis for her research paper",
			},
			{
				word: "Argument",
				translation: "Luận điểm",
				mean: "A reason or set of reasons given in support of an idea",
				pronunciation: "ˈɑːɡ.jə.mənt",
				example: "She presented a compelling argument in her essay",
			},
			{
				word: "Revision",
				translation: "Sửa đổi",
				mean: "The action of revising",
				pronunciation: "rɪˈvɪʒ.ən",
				example: "He made several revisions to his essay before submitting it",
			},
		],
	},
];
