export const farm = {
  collectionID: "03",
  name: "Farm",
  desc: "This is a collection of vocabulary related to farm operations and agricultural activities",
  value: 30,
  vocabulary: [
    {
      word: "TRACTOR",
      translation: "máy kéo",
      mean: "a powerful vehicle used for pulling farm machinery or trailers",
      pronunciation: "ˈtræktər",
      example: "The farmer used the tractor to plow the field.",
    },
    {
      word: "HARVEST",
      translation: "thu hoạch",
      mean: "the process or period of gathering in crops",
      pronunciation: "ˈhɑːrvɪst",
      example: "We expect to start the wheat harvest next week.",
    },
    {
      word: "CROP",
      translation: "cây trồng",
      mean: "a cultivated plant that is grown on a large scale commercially, especially a cereal, fruit, or vegetable",
      pronunciation: "krɒp",
      example: "This year's corn crop was very productive.",
    },
    {
      word: "BARN",
      translation: "chuồng trại",
      mean: "a large farm building used for storing grain, hay, or straw or for housing livestock",
      pronunciation: "bɑːrn",
      example: "The old barn was filled with hay bales.",
    },
    {
      word: "ORGANIC FARMING",
      translation: "nông nghiệp hữu cơ",
      mean: "farming without the use of synthetic chemicals",
      pronunciation: "ɔːˈɡænɪk ˈfɑːmɪŋ",
      example: "Organic farming practices are better for the environment.",
    },
    {
      word: "DAIRY",
      translation: "trang trại nuôi bò sữa",
      mean: "a building or establishment for processing or selling milk and milk products",
      pronunciation: "ˈdeəri",
      example: "They run a small dairy farm with about fifty cows.",
    },
    {
      word: "IRRIGATION",
      translation: "tưới tiêu",
      mean: "the supply of water to land or crops to help growth, typically by means of channels",
      pronunciation: "ˌɪrɪˈɡeɪʃn",
      example: "Irrigation systems can help conserve water in dry regions.",
    },
    {
      word: "LIVESTOCK",
      translation: "vật nuôi",
      mean: "farm animals regarded as an asset",
      pronunciation: "ˈlaɪvstɒk",
      example:
        "Raising livestock is a major source of income for rural families.",
    },
    {
      word: "PLOW",
      translation: "cày",
      mean: "a farm tool having one or several heavy blades to break the soil and cut a furrow prior to sowing",
      pronunciation: "plaʊ",
      example: "The farmer plowed the field in preparation for planting.",
    },
    {
      word: "FERTILIZER",
      translation: "phân bón",
      mean: "a chemical or natural substance added to soil or land to increase its fertility",
      pronunciation: "ˈfɜːrtɪlaɪzə",
      example: "Organic fertilizers are often made from animal manure.",
    },
    {
      word: "PASTURE",
      translation: "đồng cỏ",
      mean: "land covered with grass and other low plants suitable for grazing animals, especially cattle or sheep",
      pronunciation: "ˈpæstʃər",
      example: "The cattle grazed peacefully in the pasture.",
    },
    {
      word: "HAY",
      translation: "cỏ khô",
      mean: "grass that has been mown and dried for use as fodder",
      pronunciation: "heɪ",
      example: "They stored the hay in the barn for winter feeding.",
    },
    {
      word: "POULTRY",
      translation: "gia cầm",
      mean: "domestic fowl, such as chickens, turkeys, ducks, and geese",
      pronunciation: "ˈpoʊltri",
      example: "The poultry are kept in a coop to protect them from predators.",
    },
    {
      word: "GREENHOUSE",
      translation: "nhà kính",
      mean: "a glass building in which plants are grown that need protection from cold weather",
      pronunciation: "ˈɡriːnhaʊs",
      example: "They grow tomatoes and cucumbers in a greenhouse.",
    },
    {
      word: "SOW",
      translation: "gieo trồng",
      mean: "plant (seed) by scattering it on or in the earth",
      pronunciation: "soʊ",
      example: "It's time to sow the seeds for the spring garden.",
    },
    {
      word: "PRUNE",
      translation: "tỉa cành",
      mean: "trim (a tree, shrub, or bush) by cutting away dead or overgrown branches or stems, especially to encourage growth",
      pronunciation: "pruːn",
      example: "Pruning the apple trees helps improve their fruit production.",
    },
    {
      word: "MANURE",
      translation: "phân chuồng",
      mean: "animal dung used for fertilizing land",
      pronunciation: "məˈnjʊər",
      example: "Manure from the cattle is used to fertilize the fields.",
    },
    {
      word: "HORTICULTURE",
      translation: "nghề làm vườn",
      mean: "the art or practice of garden cultivation and management",
      pronunciation: "ˈhɔːrtɪkʌltʃər",
      example:
        "She studied horticulture to learn more about growing fruits and vegetables.",
    },
    {
      word: "AQUACULTURE",
      translation: "nuôi trồng thủy sản",
      mean: "the rearing of aquatic animals or the cultivation of aquatic plants for food",
      pronunciation: "ˈækwəˌkʌltʃər",
      example:
        "Aquaculture is becoming an increasingly important source of global seafood.",
    },
    {
      word: "AGRONOMY",
      translation: "khoa nông học",
      mean: "the science of soil management and the production of field crops",
      pronunciation: "əˈɡrɒnəmi",
      example: "Advances in agronomy have greatly increased crop yields.",
    },
    {
      word: "TILLAGE",
      translation: "sự cày cấy",
      mean: "the preparation of land for growing crops",
      pronunciation: "ˈtɪlɪdʒ",
      example:
        "Tillage can help control weeds and prepare the soil for planting.",
    },
    {
      word: "COMPOST",
      translation: "phân compost",
      mean: "decayed organic material used as a plant fertilizer",
      pronunciation: "ˈkɒmpɒst",
      example: "Compost adds important nutrients back into the garden soil.",
    },
    {
      word: "BEEKEEPING",
      translation: "nuôi ong",
      mean: "the activity or occupation of keeping bees, especially for the production of honey",
      pronunciation: "ˈbiːˌkiːpɪŋ",
      example: "Beekeeping is essential for pollination and honey production.",
    },
    {
      word: "MILKING",
      translation: "vắt sữa",
      mean: "to draw milk from (a cow or other animal), either by hand or mechanically",
      pronunciation: "ˈmɪlkɪŋ",
      example: "Milking the cows is done twice a day on the farm.",
    },
    {
      word: "SHEARING",
      translation: "cắt lông cừu",
      mean: "the cutting off of the woolen fleece of sheep",
      pronunciation: "ˈʃɪərɪŋ",
      example:
        "Shearing is typically done in the spring to keep the sheep cool during the summer.",
    },
    {
      word: "VETERINARY",
      translation: "thú y",
      mean: "relating to the medical care and treatment of animals",
      pronunciation: "ˈvɛtərɪˌnɛri",
      example:
        "Veterinary care is crucial for maintaining the health of farm animals.",
    },
    {
      word: "STABLE",
      translation: "chuồng ngựa",
      mean: "a building in which horses are kept",
      pronunciation: "ˈsteɪbəl",
      example: "The stable houses several horses and ponies.",
    },
    {
      word: "COOP",
      translation: "chuồng gà",
      mean: "a cage or pen for poultry",
      pronunciation: "kuːp",
      example:
        "The chickens are kept in a coop to protect them from predators.",
    },
    {
      word: "FENCE",
      translation: "hàng rào",
      mean: "a barrier, railing, or other upright structure, typically of wood or wire, enclosing an area of ground to prevent or control access or escape",
      pronunciation: "fɛns",
      example:
        "We need to repair the fence to keep the livestock from wandering off.",
    },
    {
      word: "FEED",
      translation: "thức ăn cho vật nuôi",
      mean: "food for farm animals",
      pronunciation: "fiːd",
      example: "Proper feed is important for the health of the animals.",
    },
  ],
};
