export const traffic = {
  collectionID: "16",
  name: "Traffic",
  desc: "This is a collection of Traffic-related vocabulary",
  value: 30,
  vocabulary: [
    {
      word: "ACCIDENT",
      translation: "tai nạn",
      mean: "an unfortunate incident that happens unexpectedly and unintentionally, typically resulting in damage or injury",
      pronunciation: "ˈæksɪdənt",
      example: "There was a major accident on the highway this morning.",
    },
    {
      word: "BICYCLE",
      translation: "xe đạp",
      mean: "a vehicle composed of two wheels held in a frame one behind the other, propelled by pedals and steered with handlebars attached to the front wheel",
      pronunciation: "ˈbaɪsɪkl",
      example:
        "Many city dwellers use bicycles as an efficient mode of transport.",
    },
    {
      word: "COMMUTE",
      translation: "đi làm",
      mean: "travel some distance between one's home and place of work on a regular basis",
      pronunciation: "kəˈmjuːt",
      example: "She commutes to work every day by train.",
    },
    {
      word: "CONGESTION",
      translation: "tắc nghẽn",
      mean: "overcrowding; clogging",
      pronunciation: "kənˈdʒɛstʃən",
      example:
        "Traffic congestion during rush hour is a common issue in large cities.",
    },
    {
      word: "CROSSWALK",
      translation: "vạch qua đường",
      mean: "a marked part of a road where pedestrians have the right of way to cross",
      pronunciation: "ˈkrɔːswɔːk",
      example: "Always use the crosswalk to cross the street safely.",
    },
    {
      word: "DETOUR",
      translation: "đường vòng",
      mean: "a long or roundabout route taken to avoid something or to visit somewhere along the way",
      pronunciation: "ˈdiːtʊər",
      example: "The detour added an extra ten minutes to our trip.",
    },
    {
      word: "HIGHWAY",
      translation: "đường cao tốc",
      mean: "a main road, especially one connecting major towns or cities",
      pronunciation: "ˈhaɪweɪ",
      example: "The highway is the fastest route to the city.",
    },
    {
      word: "INTERSECTION",
      translation: "ngã tư",
      mean: "a point at which two or more roads cross each other",
      pronunciation: "ˌɪntərˈsɛkʃən",
      example: "The accident occurred at a busy intersection downtown.",
    },
    {
      word: "LANE",
      translation: "làn đường",
      mean: "a narrow road in the countryside or in a town",
      pronunciation: "leɪn",
      example: "The right lane is closed for construction.",
    },
    {
      word: "LICENSE PLATE",
      translation: "biển số xe",
      mean: "a metal or plastic plate attached to a vehicle for official identification purposes",
      pronunciation: "ˈlaɪsəns pleɪt",
      example: "We need to renew our license plate next month.",
    },
    {
      word: "MOTORWAY",
      translation: "đường ô tô cao tốc",
      mean: "a long, wide road, usually used by traffic traveling fast",
      pronunciation: "ˈməʊtərweɪ",
      example: "Motorways are the quickest way to travel between cities.",
    },
    {
      word: "PARKING",
      translation: "bãi đậu xe",
      mean: "the act of stopping and disengaging a vehicle and leaving it unoccupied",
      pronunciation: "ˈpɑːrkɪŋ",
      example: "Parking in this area is extremely difficult.",
    },
    {
      word: "PEDESTRIAN",
      translation: "người đi bộ",
      mean: "a person walking along a road or in a developed area",
      pronunciation: "pɪˈdɛstrɪən",
      example: "Pedestrians should always use the sidewalk.",
    },
    {
      word: "ROUNDABOUT",
      translation: "bùng binh",
      mean: "a circular junction in which road traffic must travel in one direction around a central island",
      pronunciation: "ˈraʊndəbaʊt",
      example:
        "Take the second exit at the roundabout to continue on the main road.",
    },
    {
      word: "SPEED LIMIT",
      translation: "giới hạn tốc độ",
      mean: "the maximum speed at which a vehicle may legally travel on a particular stretch of road",
      pronunciation: "spiːd ˈlɪmɪt",
      example: "The speed limit here is 55 mph.",
    },
    {
      word: "TRAFFIC LIGHT",
      translation: "đèn giao thông",
      mean: "a visual signal to control the flow of traffic at intersections",
      pronunciation: "ˈtræfɪk laɪt",
      example:
        "The traffic light turned red as we approached the intersection.",
    },
    {
      word: "TRAFFIC SIGN",
      translation: "biển báo giao thông",
      mean: "a sign for the control of traffic or the information of drivers",
      pronunciation: "ˈtræfɪk saɪn",
      example: "Always obey the traffic signs to ensure safety on the roads.",
    },
    {
      word: "TUNNEL",
      translation: "đường hầm",
      mean: "an artificial underground passage, especially one built through a hill or under a building, road, or river",
      pronunciation: "ˈtʌnəl",
      example: "The tunnel connects the two sides of the city.",
    },
    {
      word: "VEHICLE",
      translation: "phương tiện",
      mean: "a thing used for transporting people or goods, especially on land, such as a car, truck, or cart",
      pronunciation: "ˈviːɪkl",
      example: "Motor vehicles must be registered with the DMV.",
    },
    {
      word: "YIELD",
      translation: "nhường đường",
      mean: "to give way to other vehicles or pedestrians",
      pronunciation: "jiːld",
      example: "You must yield to oncoming traffic when entering a roundabout.",
    },
    {
      word: "ZEBRA CROSSING",
      translation: "vạch kẻ ngang",
      mean: "a type of pedestrian crossing marked by broad stripes on the road and where vehicles must stop if pedestrians are waiting to cross",
      pronunciation: "ˈzebrə ˈkrɔːsɪŋ",
      example:
        "Children were taught to cross the road safely using zebra crossings.",
    },
    {
      word: "JUNCTION",
      translation: "giao lộ",
      mean: "a point where two or more roads meet",
      pronunciation: "ˈdʒʌŋkʃən",
      example: "There is a gas station at the junction of the two main roads.",
    },
    {
      word: "TRAFFIC JAM",
      translation: "kẹt xe",
      mean: "a line or lines of stationary or very slow-moving traffic, caused by roadworks, an accident, or heavy congestion",
      pronunciation: "ˈtræfɪk dʒæm",
      example: "I was late due to a massive traffic jam on the freeway.",
    },
    {
      word: "ONE-WAY STREET",
      translation: "đường một chiều",
      mean: "a street that vehicles can travel down in only one direction",
      pronunciation: "ˈwʌnˌweɪ striːt",
      example:
        "Remember, that's a one-way street, so you can't go back the same way.",
    },
    {
      word: "PARKING METER",
      translation: "đồng hồ đỗ xe",
      mean: "a device next to a parking space that you put money into in order to park your car there for a particular amount of time",
      pronunciation: "ˈpɑːrkɪŋ ˈmiːtər",
      example: "Ensure you have enough coins for the parking meter.",
    },
    {
      word: "PEDESTRIAN ZONE",
      translation: "khu vực đi bộ",
      mean: "an area of a city where vehicles are not allowed, intended for pedestrians only",
      pronunciation: "pɪˈdɛstrɪən zoʊn",
      example: "The pedestrian zone is filled with cafes and shops.",
    },
    {
      word: "ROADWORK",
      translation: "công trình đường",
      mean: "work such as the building or repair of roads",
      pronunciation: "ˈroʊdwɜːrk",
      example: "Expect delays due to roadwork on the main highway.",
    },
    {
      word: "TOLL",
      translation: "phí đường bộ",
      mean: "a charge payable for permission to use a particular bridge or road",
      pronunciation: "toʊl",
      example: "The toll for using the tunnel has increased this year.",
    },
    {
      word: "TRAFFIC WARDEN",
      translation: "cảnh sát giao thông",
      mean: "a person whose job is to ensure that drivers do not park illegally",
      pronunciation: "ˈtræfɪk ˈwɔːrdən",
      example:
        "The traffic warden issued a ticket to the illegally parked car.",
    },
    {
      word: "OVERPASS",
      translation: "cầu vượt",
      mean: "a road or pedestrian path that crosses over another road or railway",
      pronunciation: "ˈoʊvərpæs",
      example:
        "The new overpass will help reduce traffic congestion in the area.",
    },
  ],
};
