export const travel = {
  collectionID: "17",
  name: "Travel",
  desc: "This is a collection of Travel-related vocabulary",
  value: 30,
  vocabulary: [
    {
      word: "ACCOMMODATION",
      translation: "chỗ ở",
      mean: "a place to stay when traveling",
      pronunciation: "əˌkɒməˈdeɪʃən",
      example: "We booked our accommodation two months in advance.",
    },
    {
      word: "BACKPACK",
      translation: "ba lô",
      mean: "a bag carried by a strap on your back or shoulder",
      pronunciation: "ˈbækˌpæk",
      example: "He packed his backpack with essentials for the hiking trip.",
    },
    {
      word: "CURRENCY",
      translation: "tiền tệ",
      mean: "the money that is used in a particular country at a particular time",
      pronunciation: "ˈkʌrənsi",
      example: "Make sure to exchange some currency before you travel.",
    },
    {
      word: "DESTINATION",
      translation: "điểm đến",
      mean: "the place to which someone or something is going or being sent",
      pronunciation: "ˌdɛstɪˈneɪʃən",
      example: "Paris is one of the top tourist destinations in the world.",
    },
    {
      word: "EXPEDITION",
      translation: "cuộc thám hiểm",
      mean: "a journey taken for a specific purpose, often involving exploration",
      pronunciation: "ˌɛkspɪˈdɪʃən",
      example: "The expedition to the South Pole was a success.",
    },
    {
      word: "FLIGHT",
      translation: "chuyến bay",
      mean: "a journey made by air, especially in an airplane",
      pronunciation: "flaɪt",
      example: "Our flight to Tokyo is scheduled for 9 PM.",
    },
    {
      word: "GUIDE",
      translation: "hướng dẫn viên",
      mean: "a person who helps others to explore or travel in unfamiliar areas",
      pronunciation: "ɡaɪd",
      example: "Our guide will show us around the ancient ruins.",
    },
    {
      word: "ITINERARY",
      translation: "lịch trình",
      mean: "a planned route or journey",
      pronunciation: "aɪˈtɪnərəri",
      example: "I've emailed you the travel itinerary for your review.",
    },
    {
      word: "JOURNEY",
      translation: "hành trình",
      mean: "the act of traveling from one place to another",
      pronunciation: "ˈdʒɜːrni",
      example:
        "The journey from Hanoi to Ho Chi Minh City takes about two hours by plane.",
    },
    {
      word: "LUGGAGE",
      translation: "hành lý",
      mean: "bags, cases, and other containers that carry a traveler's belongings",
      pronunciation: "ˈlʌɡɪdʒ",
      example: "Please make sure to label all your luggage.",
    },
    {
      word: "MAP",
      translation: "bản đồ",
      mean: "a drawing of the Earth's surface, or part of that surface, showing the shape and position of different countries, political borders, natural features, and cities",
      pronunciation: "mæp",
      example: "You will need a map to navigate through the old city.",
    },
    {
      word: "NAVIGATION",
      translation: "điều hướng",
      mean: "the process or activity of accurately ascertaining one's position and planning and following a route",
      pronunciation: "ˌnævɪˈɡeɪʃən",
      example: "Good navigation is key in unfamiliar terrain.",
    },
    {
      word: "PASSPORT",
      translation: "hộ chiếu",
      mean: "an official document issued by a government, certifying the holder's identity and citizenship and entitling them to travel under its protection to and from foreign countries",
      pronunciation: "ˈpæspɔːrt",
      example:
        "Ensure your passport is valid for at least six months beyond your date of travel.",
    },
    {
      word: "RESORT",
      translation: "khu nghỉ dưỡng",
      mean: "a place that is a popular destination for vacations or recreation, or which is frequented for a particular purpose",
      pronunciation: "rɪˈzɔːrt",
      example: "We stayed at a beach resort for our summer holiday.",
    },
    {
      word: "SIGHTSEEING",
      translation: "ngắm cảnh",
      mean: "the activity of visiting places of interest in a particular location",
      pronunciation: "ˈsaɪtsiːɪŋ",
      example: "We went sightseeing around the historical city center.",
    },
    {
      word: "TOURIST",
      translation: "khách du lịch",
      mean: "a person who is traveling or visiting a place for pleasure",
      pronunciation: "ˈtʊərɪst",
      example: "The city is crowded with tourists during the festival.",
    },
    {
      word: "TRANSPORT",
      translation: "phương tiện đi lại",
      mean: "the system or means of conveying people or goods from place to place by means of a vehicle, aircraft, or ship",
      pronunciation: "ˈtrænspɔːrt",
      example: "Public transport in the city is efficient and convenient.",
    },
    {
      word: "VACATION",
      translation: "kỳ nghỉ",
      mean: "a period of time that a person spends away from home, school, or business usually in order to relax or travel",
      pronunciation: "vəˈkeɪʃən",
      example: "We are planning a vacation to Europe next summer.",
    },
    {
      word: "VOYAGE",
      translation: "chuyến đi dài",
      mean: "a long journey involving travel by sea or in space",
      pronunciation: "ˈvɔɪɪdʒ",
      example: "The voyage across the Atlantic took three weeks.",
    },
    {
      word: "WANDERLUST",
      translation: "khao khát du lịch",
      mean: "a strong desire to travel and explore the world",
      pronunciation: "ˈwɒndəˌlʌst",
      example:
        "She felt a great sense of wanderlust and planned her trip around the world.",
    },
    {
      word: "EXPLORE",
      translation: "khám phá",
      mean: "to travel over (new territory) for adventure or discovery",
      pronunciation: "ɪkˈsplɔːr",
      example: "Let's explore the local markets tomorrow.",
    },
    {
      word: "BOOKING",
      translation: "đặt chỗ",
      mean: "the act of reserving accommodations, travel, etc., or the arrangement so made",
      pronunciation: "ˈbʊkɪŋ",
      example: "Your booking is confirmed for the dates you requested.",
    },
    {
      word: "CHECK-IN",
      translation: "làm thủ tục nhận phòng",
      mean: "the process of registering your arrival at a hotel or airport",
      pronunciation: "ˈʧɛkˌɪn",
      example: "You can check in online 24 hours before your flight.",
    },
    {
      word: "DEPARTURE",
      translation: "khởi hành",
      mean: "the act of leaving, especially to start a journey",
      pronunciation: "dɪˈpɑːrtʃər",
      example: "The departure time for the train is 6:00 AM.",
    },
    {
      word: "ECOTOURISM",
      translation: "du lịch sinh thái",
      mean: "the practice of traveling to natural areas in a way that conserves the environment and improves the well-being of local people",
      pronunciation: "ˈiːkoʊˌtʊərɪzm",
      example:
        "Ecotourism is gaining popularity as an alternative to traditional tourism.",
    },
    {
      word: "FARE",
      translation: "giá vé",
      mean: "the money a passenger on public transportation has to pay",
      pronunciation: "feər",
      example: "The bus fare from here to downtown is $1.50.",
    },
    {
      word: "GLOBETROTTER",
      translation: "người đi khắp thế giới",
      mean: "a person who travels widely and frequently",
      pronunciation: "ˈɡloʊbˌtrɒtər",
      example: "As a globetrotter, he has visited over fifty countries.",
    },
    {
      word: "HOSTEL",
      translation: "nhà trọ",
      mean: "an inexpensive lodging place for travelers, especially young travelers",
      pronunciation: "ˈhɒstəl",
      example: "Staying in hostels is a great way to meet other travelers.",
    },
    {
      word: "LANDMARK",
      translation: "địa điểm nổi tiếng",
      mean: "a prominent or well-known object in a particular place",
      pronunciation: "ˈlændmɑːrk",
      example: "The Eiffel Tower is a famous landmark in Paris.",
    },
    {
      word: "TOUR",
      translation: "chuyến du lịch",
      mean: "a journey for pleasure in which several different places are visited",
      pronunciation: "tʊər",
      example: "We went on a guided tour of the city.",
    },
  ],
};
